// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SpecSelRepos.Models;
using System;

namespace SpecSelRepos.Migrations
{
    [DbContext(typeof(SpecSelResultContext))]
    [Migration("20180412120900_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpecSelRepos.Models.SpecSelResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AreaPrecisionThresholdY");

                    b.Property<string>("DataSet")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("NumResources");

                    b.Property<int>("NumSpecies");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("Output")
                        .IsRequired();

                    b.Property<decimal>("SdThresholdX");

                    b.Property<int>("SpeciesThresholdM");

                    b.HasKey("ID");

                    b.ToTable("SpecSelResult");
                });
#pragma warning restore 612, 618
        }
    }
}
